In [1]:
import sys

sys.path.append("/home/ptbadia/code/tfg/tfg_ttcross")

In [2]:
from tt_cross.src.regular_tt_cross.integrators import (
    ttrc_integrator,
    greedy_cross_integrator,
    tracked_greedycross_integrator,
    tracked_ttrc_integrator,
)
import matplotlib.pyplot as plt
import numpy as np
from tt_cross.src.utils.functions import *

In [3]:
def test_function(x: np.ndarray) -> np.ndarray:
    return np.log(np.prod(x))


def test_function(x: np.ndarray) -> float:
    return np.sin(sum(x)) * np.prod(x * np.exp(-x)) * (3 * np.linalg.norm(x) + 1 + x[0])


def test_function(x: np.ndarray) -> float:
    return np.sin(sum(x)) * np.prod(np.exp(-x))


def test_function(x: np.ndarray) -> float:
    return 1 / (1 + np.sum(x))


def test_function2(x: np.ndarray) -> np.ndarray:
    return np.prod(np.sin(x) / 2)

In [4]:
def test_function(x: np.ndarray) -> np.ndarray:
    return 2 / (
        (1 + np.sum([np.prod(x[: k + 1]) for k in range(len(x))]))
        * (1 + np.sum([np.prod(x[k:]) for k in range(len(x))]))
    )

In [5]:
integrator = tracked_ttrc_integrator(
    func=test_function,
    num_variables=8,
    intervals=np.array([[0, 1] for _ in range(8)]),
    points_per_variable=20,
    sweeps=5,
    initial_bond_guess=2,
    max_bond=16,
    quadrature="Gauss",
    truncation_tol=1e-8,
    maxvol_tol=1e-8,
)
integrator.integrate()

Initialization done after time: 0.03853559494018555 seconds and 1 tries.
Sweep 1
Sweep 2
Sweep 3
Sweep 4
Sweep 5


0.6330624259699839

In [7]:
integrator.evolution_dict

{284400: 0.6329774469104752,
 976000: 0.6317869629738803,
 1623600: 0.6338119333542727,
 2271200: 0.6261334521614164,
 2942400: 0.6330624259699839}

In [6]:
for k in range(5):
    print(integrator.i[k + 1].shape, integrator.j[k].shape)

(7, 1) (7, 5)
(12, 2) (12, 4)
(14, 3) (14, 3)
(15, 4) (15, 2)
(7, 5) (7, 1)


In [7]:
for k in range(5):
    print(integrator.non_truncated_i[k + 1].shape, integrator.non_truncated_j[k].shape)

(7, 1) (8, 5)
(12, 2) (13, 4)
(14, 3) (14, 3)
(15, 4) (15, 2)
(7, 5) (7, 1)


In [29]:
for i in integrator.i:
    print(i.shape)

(1, 1)
(4, 1)
(5, 2)
(5, 3)
(6, 4)
(8, 5)
(10, 6)
(10, 7)
(10, 8)
(6, 9)


In [30]:
for i in integrator.j:
    print(i.shape)

(5, 9)
(6, 8)
(7, 7)
(7, 6)
(7, 5)
(7, 4)
(10, 3)
(10, 2)
(6, 1)
(1, 1)


In [6]:
import matplotlib.pyplot as plt

integrator.evolution_dict.items()

dict_items([(155600, -1.0058278129172035e-18), (245200, -1.00582781291716e-18), (334800, -1.00582781291716e-18), (424400, -1.00582781291716e-18), (514000, -1.00582781291716e-18), (603600, -1.00582781291716e-18), (693200, -1.00582781291716e-18), (782800, -1.00582781291716e-18), (872400, -1.00582781291716e-18), (962000, -1.00582781291716e-18)])

In [18]:
integrator.interpolator.bonds

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2])

In [5]:
integrator = ttrc_integrator(
    func=test_function2,
    num_variables=10,
    intervals=np.array([[0, np.pi] for _ in range(10)]),
    points_per_variable=50,
    sweeps=10,
    initial_bond_guess=5,
    max_bond=20,
    quadrature="Gauss",
)
integrator.integrate()

Initialization done after time: 0.08924579620361328 seconds and 1 tries.
Sweep 1
0.04377611335512049
0.05379657083662619
0.13387531454879967
0.3394108237889981
92.34498932572372
317.8890673698318
545.2391840497813
1074.619453975836
946.9150987981648
2.0267824009235488e-13
946.9150987981646
2024.2164519374394
482.3532074775375
70.70326482905243
16.84797420591325
6.5266426137334435
1.555242274501187
0.2279671923038183
Sweep 2
1.768951411676119e-17
0.22796719230381815
1.5552422745011862
6.526642613733442
16.84797420591325
70.70326482905246
482.3532074775377
2024.21645193744
946.9150987981656
2.4092132613464846e-13
946.915098798165
2024.2164519374405
482.35320747753764
70.70326482905243
16.847974205913257
6.526642613733441
1.555242274501186
0.227967192303818
Sweep 3
1.768951411676119e-17
0.227967192303818
1.555242274501186
6.52664261373344
16.847974205913253
70.70326482905244
482.35320747753764
2024.21645193744
946.9150987981657
2.4092132613464846e-13
946.915098798165
2024.2164519374403
48

0.9999999999999588

In [20]:
integrator.interpolator.bonds

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [3]:
integrator3 = ttrc_integrator(
    func=gaussian,
    num_variables=10,
    intervals=np.array([[-5, 5] for _ in range(10)]),
    points_per_variable=10,
    sweeps=8,
    initial_bond_guess=3,
    max_bond=10,
    quadrature="Trapezoidal",
)
integrator3.integrate()

Initialization done after time: 0.009338855743408203 seconds and 1 tries.
Sweep 1
Sweep 2
Sweep 3
Sweep 4
Sweep 5
Sweep 6
Sweep 7
Sweep 8


-6.428747544568117e+111

In [7]:
for i in integrator3.interpolator.i:
    print(i.shape)

(1, 1)
(4, 1)
(7, 2)
(10, 3)
(10, 4)
(10, 5)
(10, 6)
(10, 7)
(10, 8)
(10, 9)
(9, 10)
(10, 11)
(10, 12)
(10, 13)
(10, 14)
(10, 15)
(9, 16)
(8, 17)
(7, 18)
(4, 19)


In [22]:
(2 * np.pi) ** 10

95895600.61550897

In [24]:
# In the presence of singularities, if pivot_finder_tol is too high, the integrator will select very similar
# points next to the singularity, resulting in singular matrices and a failed integration.

integrator2 = tracked_greedycross_integrator(
    func=test_function,
    num_variables=8,
    intervals=np.array([[0, 1] for _ in range(8)]),
    points_per_variable=20,
    sweeps=7,
    max_bond=15,
    quadrature="Gauss",
    pivot_finder_tol=1e-6,
)

integrator2.integrate()

Initialization done after time: 0.001119375228881836 seconds and 1 tries.
Sweep 1
Sweep 2
Sweep 3
Sweep 4
Sweep 5
Sweep 6
Sweep 7


0.6331672020673899

In [22]:
integrator2.evolution_dict

{900: 0.6310179614240838,
 2700: 0.6017800661352506,
 4500: 0.6020637047054761,
 6300: 0.6028305834768832,
 8100: 0.6041377963904624,
 9900: 0.6049422576886645,
 11700: 0.5974718109536119,
 13500: 0.627169869576381,
 15300: 0.6337546452260195,
 17100: 0.6325142581094042,
 22500: 0.6332171577735466,
 27900: 0.6334252592109914,
 33300: 0.6340600540468192,
 38700: 0.6315355897808291,
 44100: 0.6317842811452327,
 49500: 0.6319842140433489,
 54900: 0.6305935771204584,
 57600: 0.6313397966407862,
 60300: 0.6317146269130682,
 71100: 0.6302161658141177,
 81900: 0.6302453515320531,
 92700: 0.6301888283109507,
 103500: 0.630142576339874,
 114300: 0.6293149631058307,
 125100: 0.6298179407538741,
 135900: 0.6292509205246122,
 139500: 0.6296072500990719,
 143100: 0.6295738988733403,
 161100: 0.6292646123680082,
 179100: 0.6293166237463143,
 197100: 0.6291733365929473,
 215100: 0.6294235539534301,
 233100: 0.6294207289865298,
 251100: 0.629468845261777,
 269100: 0.6311931096447209,
 273600: 0.631150

In [34]:
integrator2.bonds

array([11, 15, 15, 15, 15, 14,  7])

In [11]:
for i in integrator2.i:
    print(i)

[[1.]]
[[0.0]
 [1.0]
 [0.3103448275862069]
 [0.6551724137931034]]
[[0.0 0.0]
 [1.0 0.41379310344827586]
 [0.0 0.3793103448275862]
 [1.0 1.0]]
[[0.0 0.0 0.0]
 [1.0 0.41379310344827586 0.0]
 [0.0 0.0 0.3793103448275862]
 [1.0 1.0 1.0]
 [0.0 0.0 0.13793103448275862]]
[[0.0 0.0 0.0 0.0]
 [1.0 0.41379310344827586 0.0 0.0]
 [0.0 0.0 0.0 0.3793103448275862]
 [1.0 1.0 1.0 1.0]
 [1.0 0.41379310344827586 0.0 1.0]]
[[0.0 0.0 0.0 0.0 0.0]
 [1.0 0.41379310344827586 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.3793103448275862]
 [1.0 1.0 1.0 1.0 1.0]
 [1.0 0.41379310344827586 0.0 0.0 1.0]]
[[0.0 0.0 0.0 0.0 0.0 0.0]
 [1.0 0.41379310344827586 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.3793103448275862]
 [1.0 1.0 1.0 1.0 1.0 1.0]
 [1.0 0.41379310344827586 0.0 0.0 0.0 1.0]]
[[0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [1.0 0.41379310344827586 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.3793103448275862]
 [1.0 1.0 1.0 1.0 1.0 1.0 1.0]
 [1.0 0.41379310344827586 0.0 0.0 0.0 0.0 1.0]]
[[0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [1.0 0.

In [26]:
integrator2.interpolator.bonds

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1])

In [27]:
integrator2.evolution_dict

{400: 0.1734877830521058,
 1200: 0.16366103504160545,
 2000: 0.1502779675391693,
 2800: 0.20616162438197405,
 3600: 0.15107876045022756,
 4400: 0.06102370845480326,
 5200: 0.03317247770594936,
 6000: 0.01233820553274095,
 6800: 0.028520753223377028,
 7600: 0.028520753223377028,
 9200: 0.028916388754062355,
 11600: 0.030574417290189334,
 14000: -2089308950789.7756,
 16400: -1690964813782.1316,
 18800: -1074114635654.792,
 21200: -1014927317883.8499,
 23600: 1.076008431741586e+26,
 24800: 4.418670534814469e+25,
 26000: 7.2748132362465785e+25,
 30800: 3.4106724547389498e+25,
 35600: -4.196348868854867e+25,
 40400: -5.1917328132091846e+26,
 45200: -9.862792712921169e+28,
 50000: -2.534283706344681e+26,
 54800: -1.814975499944701e+26,
 58000: -1.9507369798631683e+26,
 59600: -1.9129354439620253e+26,
 61200: -3.309052987110329e+26,
 67600: -1.1446561015462829e+25,
 75600: -4.427159086566745e+38,
 83600: -1.74994007394719e+39,
 91600: 2.8809087918151395e+39,
 99600: 2.919986106975414e+37,
 10

In [23]:
integrator2 = greedy_cross_integrator(
    func=test_function2,
    num_variables=30,
    intervals=np.array([[0, np.pi] for _ in range(30)]),
    points_per_variable=30,
    sweeps=10,
    max_bond=10,
    quadrature="Gauss",
    pivot_finder_tol=1e-12,
)

integrator2.integrate()

Initialization done after time: 0.0011169910430908203 seconds and 1 tries.
Sweep 1


0.9999999999999014

In [24]:
integrator2.interpolator.bonds

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1])