In [1]:
import sys

sys.path.append("/home/ptbadia/code/tfg/tfg_ttcross")

In [2]:
from tt_cross.src.quantic_tt_cross.integrators import greedy_qtt_cross_integrator, ttrc_qtt_integrator
import numpy as np
from ncon import ncon

In [5]:
import numpy as np

np.random.seed(0)

# Generate a random matrix


def test_function(x: np.ndarray) -> np.ndarray:
    return 2 / (
        (1 + np.sum([np.prod(x[: k + 1]) for k in range(len(x))]))
        * (1 + np.sum([np.prod(x[k:]) for k in range(len(x))]))
    )

In [118]:
def test_function(x: np.ndarray) -> np.ndarray:
    return np.prod(np.sin(x) / 2)


def test_function(x: np.ndarray) -> float:
    return 1 / (1 + np.sum(x))


def test_function(x: np.ndarray) -> float:
    return np.exp(-0.5 * x.T @ precision_matrix @ x)


# def test_function(x: np.ndarray) -> float:
#     return np.exp(-np.sum(np.tan(x)**2))

In [9]:
integrator = greedy_qtt_cross_integrator(
    func=test_function,
    num_variables=10,
    intervals=np.array([[0, 1] for _ in range(10)]),
    d=10,
    sweeps=10,
    max_bond=20,
    pivot_finder_tol=1e-8,
)

integrator.integrate()

Initialization done after time: 0.02607583999633789 seconds and 1 tries.
Sweep 1
Sweep 2
Sweep 3
Sweep 4
Sweep 5
Sweep 6
Sweep 7
Sweep 8
Sweep 9
Sweep 10


65.48401287962137

In [84]:
integrator.interpolator.bonds

array([ 2,  4,  7,  8, 12, 11, 12, 13, 12, 12,  8, 10, 11, 12, 15, 15, 17,
       16, 12,  8, 12, 11,  9,  8,  7,  6,  5,  4,  2])

In [121]:
np.sqrt(((2 * np.pi) ** 3) / np.linalg.det(precision_matrix))

36.132083238730075

In [16]:
integrator.interpolator.bonds

array([2, 4, 5, 5, 4, 4, 5, 4, 2, 1, 2, 4, 5, 5, 4, 4, 5, 4, 2, 1, 2, 4,
       5, 5, 4, 4, 5, 4, 2, 1, 2, 4, 5, 5, 4, 4, 5, 4, 2, 1, 2, 4, 5, 5,
       4, 4, 5, 4, 2, 1, 2, 4, 5, 5, 4, 4, 5, 4, 2, 1, 2, 4, 5, 5, 4, 4,
       5, 4, 2, 1, 2, 4, 5, 5, 4, 4, 5, 4, 2, 1, 2, 4, 5, 5, 4, 4, 5, 4,
       2, 1, 2, 4, 5, 5, 4, 4, 5, 4, 2])

In [7]:
integrator2 = ttrc_qtt_integrator(
    func=test_function,
    num_variables=10,
    intervals=np.array([[0, 1] for _ in range(10)]),
    d=10,
    sweeps=10,
    initial_bond_guess=3,
    max_bond=20,
)

integrator2.integrate()

/home/ptbadia/code/tfg/tfg_ttcross/tt_cross/src/regular_tt_cross/dmrg_cross.py:370: UserWarning: The initial bond guess is larger than the maximum grid size. Max bond gets initialized to the maximum of grid size instead of given initial_bond_guess.
  warnings.warn(


Initialization done after time: 0.20508670806884766 seconds and 1 tries.
Sweep 1
Sweep 2
Sweep 3
Sweep 4
Sweep 5
Sweep 6
Sweep 7
Sweep 8
Sweep 9
Sweep 10


ValueError: The left and right indexes must have the same dimension

In [126]:
integrator2.interpolator.bonds

array([ 2,  4,  8, 10, 10, 10,  9,  9,  9,  8,  8,  8,  8,  9, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,  8,
        7,  6,  5,  5,  4,  4,  4,  3,  3,  2])