In [11]:
import sys

sys.path.append("/home/ptbadia/code/tfg/tfg_ttcross")

In [2]:
import numpy as np
import numba as nb
from tt_cross.src.functions import *
from tt_cross.src.dmrg_cross import *

In [4]:
# Testing the slater function

slater(x=[1, 2, 3, 4], num_variables=4)

0.0007633268329680491

In [5]:
# grid_creation
num_var = 5
subdivision = 3
temp = [np.linspace(-1.0, 1.0, subdivision) for _ in range(5)]
grid = np.array(temp)
grid

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

In [6]:
# integrator initialization

example_integrator = greedy_cross(func=slater, num_variables=num_var, grid=grid, tol=1e-2, sweeps=3, is_f_complex=False)

In [8]:
example_integrator._create_initial_index_sets()
example_integrator.i

array([array([[1.]]), array([[1.]]), array([[1., 0.]]),
       array([[1., 0., 1.]]), array([[1., 0., 1., 0.]])], dtype=object)

In [10]:
example_integrator._create_initial_bonds()
example_integrator.compute_single_site_tensor(2)

array([[[0.06766764],
        [0.10214551],
        [0.06766764]]])