In [16]:
import sys

sys.path.append("/home/ptbadia/code/tfg/tfg_ttcross")

In [17]:
import numpy as np
import numba as nb
from tt_cross.src.functions import *
from tt_cross.src.dmrg_cross import *

In [18]:
# Testing the slater function

slater(x=[1, 2, 3, 4], num_variables=4)

0.0007633268329680491

In [19]:
# grid_creation
num_var = 40
subdivision = 25
temp = [np.linspace(1, 2, subdivision) for _ in range(num_var)]
grid = np.array(temp)
grid

array([[1.        , 1.04166667, 1.08333333, 1.125     , 1.16666667,
        1.20833333, 1.25      , 1.29166667, 1.33333333, 1.375     ,
        1.41666667, 1.45833333, 1.5       , 1.54166667, 1.58333333,
        1.625     , 1.66666667, 1.70833333, 1.75      , 1.79166667,
        1.83333333, 1.875     , 1.91666667, 1.95833333, 2.        ],
       [1.        , 1.04166667, 1.08333333, 1.125     , 1.16666667,
        1.20833333, 1.25      , 1.29166667, 1.33333333, 1.375     ,
        1.41666667, 1.45833333, 1.5       , 1.54166667, 1.58333333,
        1.625     , 1.66666667, 1.70833333, 1.75      , 1.79166667,
        1.83333333, 1.875     , 1.91666667, 1.95833333, 2.        ],
       [1.        , 1.04166667, 1.08333333, 1.125     , 1.16666667,
        1.20833333, 1.25      , 1.29166667, 1.33333333, 1.375     ,
        1.41666667, 1.45833333, 1.5       , 1.54166667, 1.58333333,
        1.625     , 1.66666667, 1.70833333, 1.75      , 1.79166667,
        1.83333333, 1.875     , 1.91666667, 1.

In [20]:
# integrator initialization

example_integrator = greedy_cross(
    func=slater, num_variables=num_var, grid=grid, tol=1e-2, max_bond=5, sweeps=3, is_f_complex=False
)

In [21]:
example_integrator._create_initial_index_sets()
example_integrator.i

array([array([[1.]]), array([[1.]]), array([[1., 1.]]),
       array([[1., 1., 1.]]), array([[1., 1., 1., 1.]]),
       array([[1., 1., 1., 1., 1.]]), array([[1., 1., 1., 1., 1., 1.]]),
       array([[1., 1., 1., 1., 1., 1., 1.]]),
       array([[1., 1., 1., 1., 1., 1., 1., 1.]]),
       array([[1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
       array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
       array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
       array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
       array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
       array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
       array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
       array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
       array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
               1.]])                                                          ,
       array([[

In [22]:
example_integrator._create_initial_bonds()
example_integrator.compute_single_site_tensor(2)

array([[[0.0002833 ],
        [0.00028111],
        [0.00027884],
        [0.00027651],
        [0.00027411],
        [0.00027165],
        [0.00026914],
        [0.00026656],
        [0.00026393],
        [0.00026125],
        [0.00025852],
        [0.00025574],
        [0.00025292],
        [0.00025005],
        [0.00024715],
        [0.00024421],
        [0.00024123],
        [0.00023822],
        [0.00023518],
        [0.00023212],
        [0.00022903],
        [0.00022592],
        [0.00022279],
        [0.00021964],
        [0.00021647]]])

In [23]:
example_integrator.index_update(2)

In [24]:
example_integrator.i[2]

array([[1., 1.]])

In [25]:
example_integrator.bonds

array([1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [26]:
example_integrator = greedy_cross(
    func=slater, num_variables=num_var, grid=grid, tol=1e-5, max_bond=10, sweeps=6, is_f_complex=False
)

example_integrator.run()

array([array([[[2.83302579e-04, 2.16474331e-04, 1.53576963e-04, 3.70496886e-05],
               [2.81105913e-04, 2.14862974e-04, 1.52489649e-04, 3.68321368e-05],
               [2.78840453e-04, 2.13200475e-04, 1.51367293e-04, 3.66072259e-05],
               [2.76508461e-04, 2.11488427e-04, 1.50210918e-04, 3.63751259e-05],
               [2.74112246e-04, 2.09728460e-04, 1.49021570e-04, 3.61360109e-05],
               [2.71654155e-04, 2.07922230e-04, 1.47800316e-04, 3.58900593e-05],
               [2.69136574e-04, 2.06071423e-04, 1.46548243e-04, 3.56374533e-05],
               [2.66561919e-04, 2.04177749e-04, 1.45266452e-04, 3.53783784e-05],
               [2.63932636e-04, 2.02242939e-04, 1.43956063e-04, 3.51130238e-05],
               [2.61251192e-04, 2.00268744e-04, 1.42618208e-04, 3.48415816e-05],
               [2.58520077e-04, 1.98256930e-04, 1.41254029e-04, 3.45642468e-05],
               [2.55741794e-04, 1.96209276e-04, 1.39864682e-04, 3.42812169e-05],
               [2.52918857e-

In [27]:
example_integrator.bonds

array([4, 4, 4, 4, 4, 4, 4, 5, 5, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 3])