In [1]:
import sys

sys.path.append("/home/ptbadia/code/tfg/tfg_ttcross")

In [2]:
import numpy as np
import numba as nb
from tt_cross.src.functions import *
from tt_cross.src.dmrg_cross import *

In [3]:
# Testing the slater function

slater(x=[1, 2, 3, 4], num_variables=4)

0.0007633268329680491

In [14]:
# grid_creation
num_var = 8
subdivision = 3
temp = [np.linspace(1, 2, subdivision) for _ in range(num_var)]
grid = np.array(temp)
grid

array([[1. , 1.5, 2. ],
       [1. , 1.5, 2. ],
       [1. , 1.5, 2. ],
       [1. , 1.5, 2. ],
       [1. , 1.5, 2. ],
       [1. , 1.5, 2. ],
       [1. , 1.5, 2. ],
       [1. , 1.5, 2. ]])

In [15]:
# integrator initialization

example_integrator = greedy_cross(
    func=slater, num_variables=num_var, grid=grid, tol=1e-2, max_bond=5, sweeps=3, is_f_complex=False
)

In [16]:
example_integrator._create_initial_index_sets()
example_integrator.i

array([array([[1.]]), array([[2.]]), array([[2. , 1.5]]),
       array([[2. , 1.5, 1. ]]), array([[2. , 1.5, 1. , 1. ]]),
       array([[2. , 1.5, 1. , 1. , 1. ]]),
       array([[2. , 1.5, 1. , 1. , 1. , 1.5]]),
       array([[2. , 1.5, 1. , 1. , 1. , 1.5, 1. ]])], dtype=object)

In [17]:
example_integrator._create_initial_bonds()
example_integrator.compute_single_site_tensor(2)

array([[[0.00293479],
        [0.00246867],
        [0.00195779]]])

In [18]:
example_integrator.index_update(2)

In [19]:
example_integrator.i[2]

array([[2. , 1.5]])

In [20]:
example_integrator.bonds

array([1, 1, 2, 1, 1, 1, 1])

In [21]:
example_integrator = greedy_cross(
    func=slater, num_variables=num_var, grid=grid, tol=1e-2, max_bond=5, sweeps=3, is_f_complex=False
)

example_integrator.run()

array([array([[[0.00423785, 0.00273647, 0.00351306],
               [0.00351306, 0.00230773, 0.00293479],
               [0.00273647, 0.00183599, 0.00230773]]]),
       array([[[0.00423785, 0.00690452, 0.00559325, 0.00753628, 0.00351306],
               [0.00351306, 0.00559325, 0.00457891, 0.00607669, 0.00293479],
               [0.00273647, 0.00423785, 0.00351306, 0.00457891, 0.00230773]],

              [[0.00273647, 0.00423785, 0.00351306, 0.00457891, 0.00230773],
               [0.00230773, 0.00351306, 0.00293479, 0.00378308, 0.00195779],
               [0.00183599, 0.00273647, 0.00230773, 0.00293479, 0.0015692 ]],

              [[0.00351306, 0.00559325, 0.00457891, 0.00607669, 0.00293479],
               [0.00293479, 0.00457891, 0.00378308, 0.00495467, 0.00246867],
               [0.00230773, 0.00351306, 0.00293479, 0.00378308, 0.00195779]]]),
       array([[[0.00423785, 0.00690452, 0.00457891, 0.00559325, 0.00351306],
               [0.00351306, 0.00559325, 0.00378308, 0.0045789