In [1]:
import sys

sys.path.append("..")

In [2]:
from src.integrators import ttrc_integrator, greedy_cross_integrator
import matplotlib.pyplot as plt
import numpy as np

In [16]:
def test_function(x: np.ndarray) -> np.ndarray:
    return np.log(np.prod(x))


def test_function2(x: np.ndarray) -> np.ndarray:
    return np.prod(np.sin(x) / 2)

In [17]:
integrator = ttrc_integrator(
    func=test_function,
    num_variables=30,
    intervals=np.array([[0, 1] for _ in range(50)]),
    points_per_variable=20,
    sweeps=10,
    initial_bond_guess=5,
    max_bond=10,
    quadrature="Gauss",
)
integrator.integrate()

Initialization done after time: 0.10164618492126465 seconds and 1 tries.
Sweep 1
Sweep 2
Sweep 3
Sweep 4
Sweep 5
Sweep 6
Sweep 7
Sweep 8
Sweep 9
Sweep 10


-29.95490857500693

In [18]:
integrator.interpolator.bonds

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2])

In [19]:
integrator = ttrc_integrator(
    func=test_function2,
    num_variables=10,
    intervals=np.array([[0, np.pi] for _ in range(10)]),
    points_per_variable=50,
    sweeps=10,
    initial_bond_guess=5,
    max_bond=20,
    quadrature="Gauss",
)
integrator.integrate()

Initialization done after time: 0.11617398262023926 seconds and 1 tries.
Sweep 1
Sweep 2
Sweep 3
Sweep 4
Sweep 5
Sweep 6
Sweep 7
Sweep 8
Sweep 9
Sweep 10


0.9999999999999588

In [20]:
integrator.interpolator.bonds

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [21]:
# In the presence of singularities, if pivot_finder_tol is too high, the integrator will select very similar
# points next to the singularity, resulting in singular matrices and a failed integration.

integrator2 = greedy_cross_integrator(
    func=test_function,
    num_variables=100,
    intervals=np.array([[0, 1] for _ in range(100)]),
    points_per_variable=40,
    sweeps=10,
    max_bond=10,
    quadrature="Gauss",
    pivot_finder_tol=1e-10,
)

integrator2.integrate()

Initialization done after time: 0.002011537551879883 seconds and 1 tries.
Sweep 1
Sweep 2


-99.96150267868836

In [22]:
integrator2.interpolator.bonds

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [23]:
integrator2 = greedy_cross_integrator(
    func=test_function2,
    num_variables=30,
    intervals=np.array([[0, np.pi] for _ in range(30)]),
    points_per_variable=30,
    sweeps=10,
    max_bond=10,
    quadrature="Gauss",
    pivot_finder_tol=1e-12,
)

integrator2.integrate()

Initialization done after time: 0.0011169910430908203 seconds and 1 tries.
Sweep 1


0.9999999999999014

In [24]:
integrator2.interpolator.bonds

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1])