In [1]:
import sys

sys.path.append("/home/ptbadia/code/tfg/tfg_ttcross")

In [2]:
import numpy as np
import numba as nb
from tt_cross.src.maxvol import maxvol, py_maxvol, greedy_pivot_finder

In [3]:
a = np.random.rand(20, 5)

In [4]:
print(a)

[[0.56566628 0.47470087 0.19240306 0.89842917 0.266371  ]
 [0.24895154 0.43493916 0.11614651 0.61046208 0.70385251]
 [0.32198972 0.0258362  0.15953934 0.36979746 0.57948239]
 [0.03884833 0.61092774 0.3216551  0.91825579 0.87211207]
 [0.41530284 0.80955266 0.51851756 0.6493621  0.61363095]
 [0.34373841 0.38011535 0.41799937 0.73239134 0.52329367]
 [0.82584365 0.21271265 0.59345398 0.54515985 0.12426817]
 [0.05934437 0.14522902 0.35185275 0.40600752 0.90643807]
 [0.84530106 0.53788941 0.26259388 0.97831015 0.32003486]
 [0.9652253  0.57112506 0.2537893  0.14034638 0.33251212]
 [0.80983749 0.13899222 0.80263623 0.32896231 0.32392046]
 [0.75558823 0.2140037  0.62505302 0.88363674 0.89204939]
 [0.88160064 0.90667833 0.47543369 0.99153791 0.25566855]
 [0.16351708 0.83216814 0.21902901 0.1536171  0.0866799 ]
 [0.03325895 0.09463358 0.64829666 0.86437478 0.55608189]
 [0.03939583 0.06262361 0.61288786 0.02013346 0.03562884]
 [0.51435438 0.66573297 0.6204321  0.24345818 0.7017735 ]
 [0.40160002 0

In [5]:
# %%timeit
strings = np.array(
    ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t"], dtype=object
)
rows, best_indices = py_maxvol(a, old_index_set=strings, tol=1.005, max_iters=1000)
print(rows)

abs(np.linalg.det(a[rows]))

[19 13 18  8  3]


0.44881015941025776

In [6]:
best_indices

array(['t', 'n', 's', 'i', 'd'], dtype=object)

In [7]:
rows = maxvol(a, tol=1.005, max_iter=1000)

[ 9 13 17  8  3  5  6  7  4  0 10 11 12  1 14 15 16  2 18 19]
[[ 1.00000000e+00 -1.06546850e-16 -6.99554268e-18 -4.48572534e-17
   5.82038994e-17]
 [ 2.87555409e-17  1.00000000e+00  4.37221417e-19  2.80357834e-18
  -3.63774371e-18]
 [-8.05193143e-17  1.31092406e-16  1.00000000e+00  4.48572534e-17
  -5.82038994e-17]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
   5.45661557e-18]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00]
 [ 9.90952196e-02  1.15571414e-02  2.86562850e-01  1.49735176e-01
   2.02598936e-01]
 [-7.35807268e-02  7.71819094e-01  6.72456271e-01  6.43726354e-01
  -1.18436896e+00]
 [ 8.67938629e-01 -1.31324265e+00  2.63746115e-01 -7.95354624e-01
   8.19907383e-01]
 [ 4.13958567e-01  4.19778180e-01  9.28848138e-02 -1.03210285e-01
   2.81468141e-01]
 [-3.07688699e-01  1.81545143e-01 -2.42787196e-02  9.74204168e-01
   2.29000383e-01]
 [ 4.19524941e-01  5.50638575e-01  9.44756249e-01  5.00594743e-03
  -1.40807919e+00]
 [ 

In [8]:
abs(np.linalg.det(a[rows[0]]))

0.15091852804016956