In [1]:
import sys

sys.path.append("/home/ptbadia/code/tfg/tfg_ttcross")

In [2]:
import numpy as np
import numba as nb
from tt_cross.src.maxvol import maxvol, py_maxvol, greedy_pivot_finder

In [3]:
a = np.random.rand(20, 4)

In [4]:
print(a)

[[0.9288699  0.04839741 0.67407343 0.13912082]
 [0.58514335 0.76571382 0.81612576 0.25107157]
 [0.76484201 0.31081898 0.0713807  0.85626594]
 [0.91704731 0.65480545 0.55338784 0.85519497]
 [0.58939789 0.6311656  0.72907358 0.59142165]
 [0.27437746 0.89908071 0.40605285 0.55518731]
 [0.88625031 0.68536406 0.2106607  0.33822842]
 [0.50872708 0.94992279 0.55234661 0.32597592]
 [0.51737338 0.38883545 0.11071372 0.15321903]
 [0.1315357  0.77490742 0.46309921 0.32856553]
 [0.28044316 0.82642694 0.52046569 0.72800004]
 [0.74190276 0.89604852 0.73951885 0.25560439]
 [0.46569874 0.116796   0.48571494 0.4890435 ]
 [0.09399897 0.25622258 0.81391658 0.58644394]
 [0.05327252 0.46007605 0.83842596 0.11417506]
 [0.71993869 0.4101524  0.22399921 0.42323251]
 [0.98231051 0.12883488 0.40689758 0.62196432]
 [0.59198841 0.19445316 0.98793609 0.39407083]
 [0.36729243 0.0372521  0.31015776 0.13671691]
 [0.88300579 0.82206756 0.86515826 0.43177268]]


In [5]:
# %%timeit
my_rows = maxvol(a, tol=2, max_iter=1000)[0]
print(my_rows)

abs(np.linalg.det(a[my_rows]))

[ 6 14 17 19  4  5  0  7  8  9 10 11 12 13  1 15 16  2 18  3]
[[ 3.34229290e-01  1.98626413e-01  5.35499723e-01  2.09921639e-01
   7.31182524e-01  6.58658297e-01  1.00000000e+00 -2.22188687e-01
   6.09678437e-01  5.66907312e-01 -9.77660048e-02  6.82009683e-01
   1.16034915e-01  3.80633980e-01 -7.63278329e-17  7.21084197e-01
   1.72149950e-02  0.00000000e+00  1.92557840e-01  0.00000000e+00]
 [ 7.30206328e-01  9.05064249e-01  8.61201404e-01  1.08540620e+00
   8.98584281e-01 -5.01985513e-01  0.00000000e+00 -3.56369984e-01
   5.35958628e-02 -4.82903838e-01  5.19839018e-01  1.59868214e-01
  -5.56902159e-01 -7.91388192e-03  1.00000000e+00 -5.41024190e-02
  -1.53926893e-02  0.00000000e+00  9.77425912e-02  0.00000000e+00]
 [ 1.28163121e-01  2.20915102e-01  8.20123107e-01  1.61714194e-01
  -8.17750153e-01  6.87808463e-02  0.00000000e+00  7.98933150e-01
  -3.27523665e-01  2.29889880e-01  2.77183701e-01 -1.65679260e-01
   7.30205260e-01  4.24524180e-01  1.40562660e-16  5.99051927e-01
   1.6859867

IndexError: index 5 is out of bounds for axis 0 with size 4

In [ ]:
# %%timeit
rows = py_maxvol(a, tol=2, max_iters=1000)[0]
print(rows)

abs(np.linalg.det(a[rows]))

[ 4 10  1  3  0  5  6  7  8  9  2 11 12 13 14 15 16 17 18 19]
[[ 3.84217935e-01  1.10477745e-01  6.19107712e-01 -2.63960086e-01]
 [ 1.04843186e-16  2.77555756e-17  1.00000000e+00  0.00000000e+00]
 [ 8.14382561e-01  7.08072228e-01 -4.61543261e-01  1.45966322e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-8.70594513e-02 -3.65721056e-01  2.59365281e-01  5.70927437e-01]
 [ 2.56008296e-01  2.43641387e-01  3.79886270e-02  6.78423939e-01]
 [-6.13880665e-01  3.77697684e-01  7.45936444e-01  1.58629694e-01]
 [-2.61550495e-01  6.04518410e-01  1.27568090e-01  4.65391496e-01]
 [ 6.82027712e-01  9.24198145e-01 -6.81427385e-02 -1.13057289e-01]
 [-8.32667268e-17  1.00000000e+00  1.79655259e-16  7.82757287e-18]
 [ 7.43852971e-01 -3.46569975e-01  1.54370029e-01  1.77758719e-01]
 [-1.61952360e-01  5.75742650e-01  3.14867149e-01 -3.56825207e-02]
 [ 7.05483436e-01  7.99613288e-01  3.35345064e-02 -5.94068033e-01]


0.4531322895565807