In [5]:
import sys

sys.path.append("/home/ptbadia/code/tfg/tfg_ttcross")

In [6]:
import numpy as np
import numba as nb
import matplotlib.pyplot as plt
from tt_cross.src.functions import *
from tt_cross.src.dmrg_cross import *

In [7]:
# grid_creation
num_var = 10
subdivision = 30
temp = [np.linspace(0.5, 2, subdivision) for _ in range(num_var)]
grid = np.array(temp)
grid

array([[0.5       , 0.55172414, 0.60344828, 0.65517241, 0.70689655,
        0.75862069, 0.81034483, 0.86206897, 0.9137931 , 0.96551724,
        1.01724138, 1.06896552, 1.12068966, 1.17241379, 1.22413793,
        1.27586207, 1.32758621, 1.37931034, 1.43103448, 1.48275862,
        1.53448276, 1.5862069 , 1.63793103, 1.68965517, 1.74137931,
        1.79310345, 1.84482759, 1.89655172, 1.94827586, 2.        ],
       [0.5       , 0.55172414, 0.60344828, 0.65517241, 0.70689655,
        0.75862069, 0.81034483, 0.86206897, 0.9137931 , 0.96551724,
        1.01724138, 1.06896552, 1.12068966, 1.17241379, 1.22413793,
        1.27586207, 1.32758621, 1.37931034, 1.43103448, 1.48275862,
        1.53448276, 1.5862069 , 1.63793103, 1.68965517, 1.74137931,
        1.79310345, 1.84482759, 1.89655172, 1.94827586, 2.        ],
       [0.5       , 0.55172414, 0.60344828, 0.65517241, 0.70689655,
        0.75862069, 0.81034483, 0.86206897, 0.9137931 , 0.96551724,
        1.01724138, 1.06896552, 1.12068966, 1.

In [8]:
ttrc_interpolator = ttrc(
    func=slater,
    num_variables=num_var,
    grid=grid,
    maxvol_tol=1,
    truncation_tol=1e-10,
    sweeps=5,
    initial_bond_guess=10,
)

In [9]:
for i in ttrc_interpolator.i:
    print(i.shape)

(1, 1)
(10, 1)
(10, 2)
(10, 3)
(10, 4)
(10, 5)
(10, 6)
(10, 7)
(10, 8)
(10, 9)
(10, 10)


In [10]:
for j in ttrc_interpolator.j:
    print(j.shape)

(10, 9)
(10, 8)
(10, 7)
(10, 6)
(10, 5)
(10, 4)
(10, 3)
(10, 2)
(10, 1)
(1, 1)


In [11]:
ttrc_interpolator.bonds

array([10, 10, 10, 10, 10, 10, 10, 10, 10])

In [12]:
for t in ttrc_interpolator.b:
    print(t.shape)

(1, 30, 10)
(10, 30, 10)
(10, 30, 10)
(10, 30, 10)
(10, 30, 10)
(10, 30, 10)
(10, 30, 10)
(10, 30, 10)
(10, 30, 10)
(10, 30, 1)


In [13]:
ttrc_interpolator.p[-1]

array([[1.]])

In [14]:
ttrc_interpolator.initial_sweep()

In [15]:
for i in range(1, num_var):
    a = ncon([ttrc_interpolator.b[i], ttrc_interpolator.b[i]], [[-1, 1, 2], [-2, 1, 2]])
    print(a)
    print("=============")

[[ 1.00000000e+00 -2.77555756e-17  3.46944695e-17 -2.77555756e-17
   4.51028104e-17 -6.24500451e-17 -1.38777878e-17  8.67361738e-19
   3.31765865e-17 -4.85722573e-17]
 [-2.77555756e-17  1.00000000e+00 -2.22044605e-16  1.38777878e-16
  -5.55111512e-17  0.00000000e+00  8.32667268e-17 -3.81639165e-17
  -2.77555756e-17  4.51028104e-17]
 [ 3.46944695e-17 -2.22044605e-16  1.00000000e+00 -7.63278329e-17
   5.89805982e-17  1.49186219e-16 -6.24500451e-17 -6.93889390e-18
   3.46944695e-17  0.00000000e+00]
 [-2.77555756e-17  1.38777878e-16 -7.63278329e-17  1.00000000e+00
   3.46944695e-18 -1.73472348e-17  6.93889390e-18 -4.16333634e-17
  -8.32667268e-17 -5.89805982e-17]
 [ 4.51028104e-17 -5.55111512e-17  5.89805982e-17  3.46944695e-18
   1.00000000e+00 -3.46944695e-17  2.77555756e-17 -4.85722573e-17
  -5.55111512e-17 -2.25514052e-17]
 [-6.24500451e-17  0.00000000e+00  1.49186219e-16 -1.73472348e-17
  -3.46944695e-17  1.00000000e+00 -6.93889390e-17 -4.85722573e-17
   6.93889390e-18  5.55111512e-17

In [16]:
for site in range(num_var - 1):
    ttrc_interpolator.left_right_update(site)

In [17]:
for p in ttrc_interpolator.p:
    print(p.shape)

(1, 1)
(6, 6)
(7, 7)
(7, 7)
(8, 8)
(8, 8)
(9, 9)
(9, 9)
(8, 8)
(6, 6)
(1, 1)


In [18]:
for b in ttrc_interpolator.b:
    print(b.shape)

(1, 30, 6)
(6, 30, 7)
(7, 30, 7)
(7, 30, 8)
(8, 30, 8)
(8, 30, 9)
(9, 30, 9)
(9, 30, 8)
(8, 30, 6)
(6, 30, 1)


In [19]:
for site in range(num_var - 2, -1, -1):
    ttrc_interpolator.right_left_update(site)

In [20]:
for p in ttrc_interpolator.p:
    print(p.shape)

(1, 1)
(4, 4)
(4, 4)
(5, 5)
(5, 5)
(7, 7)
(9, 9)
(9, 9)
(8, 8)
(6, 6)
(1, 1)


In [21]:
ttrc_interpolator.bonds

array([4, 4, 5, 5, 7, 9, 9, 8, 6])

In [27]:
ttrc_interpolator = ttrc(
    func=slater,
    num_variables=num_var,
    grid=grid,
    maxvol_tol=1,
    truncation_tol=1e-10,
    sweeps=5,
    initial_bond_guess=10,
)

mps_ttrc = ttrc_interpolator.run()

Sweep 1
Sweep 2
Sweep 3
Sweep 4
Sweep 5


In [29]:
for t in mps_ttrc:
    print(t.shape)

(1, 30, 6)
(6, 6)
(6, 30, 7)
(7, 7)
(7, 30, 7)
(7, 7)
(7, 30, 8)
(8, 8)
(8, 30, 8)
(8, 8)
(8, 30, 9)
(9, 9)
(9, 30, 9)
(9, 9)
(9, 30, 8)
(8, 8)
(8, 30, 6)
(6, 6)
(6, 30, 1)
