In [1]:
import sys

sys.path.append("/home/ptbadia/code/tfg/tfg_ttcross")

In [2]:
import numpy as np
import numba as nb
from tt_cross.src.maxvol import maxvol, py_maxvol, greedy_pivot_finder

In [3]:
a = np.random.rand(20, 5)

In [4]:
print(a)

[[2.54165487e-01 2.96792712e-01 2.92750350e-01 8.29334680e-01
  1.77553490e-01]
 [8.44955307e-01 1.06721114e-01 3.31649691e-01 5.08909409e-01
  2.10240772e-01]
 [7.80964646e-01 9.68136203e-01 6.08120405e-02 7.79138059e-01
  7.92165673e-01]
 [7.33800111e-01 3.83155420e-01 7.78799986e-01 7.17527912e-01
  4.60601410e-02]
 [8.26707084e-01 5.20403599e-04 9.21290925e-01 6.53635498e-01
  1.37663728e-01]
 [4.54372742e-01 4.26907160e-01 6.95263543e-01 7.62604747e-01
  7.98752109e-01]
 [7.58948601e-01 1.97018089e-02 6.89533221e-01 6.21042377e-01
  7.63549262e-01]
 [4.82685217e-01 1.50018805e-01 6.96373507e-01 5.42326572e-01
  8.03297809e-01]
 [8.66517611e-01 1.71768367e-02 1.43478631e-01 3.68502677e-01
  5.92046184e-01]
 [8.13979056e-01 8.83054531e-01 7.44903214e-01 3.22618688e-01
  7.93003003e-01]
 [1.74541239e-01 6.50140985e-01 1.17902864e-01 3.71363664e-01
  6.07732098e-02]
 [9.56729439e-01 9.60652316e-01 1.57818750e-02 1.82348579e-02
  2.52964131e-01]
 [8.01717770e-01 3.11268400e-01 7.024532

In [7]:
rows, _ = maxvol(a, 1.005, 1000)
print(rows)
print(np.linalg.det(a[rows]))

[13  2 16 11  3  5  6  7  8  9 10  4 12  0 14 15  1 17 18 19]
[13  2 16 11  3]
0.40443443373259247


In [14]:
# %%timeit
strings = np.array(
    ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t"], dtype=object
)
rows, best_indices = py_maxvol(a, full_index_set=strings, tol=1.005, max_iters=1000)
print(rows)

abs(np.linalg.det(a[rows]))

[ 8  2  9 15  3]


0.5250925634116863

In [26]:
import numpy as np


def concatenate_arrays(arr1, arr2):
    arr1 = np.array(arr1)
    arr2 = np.array(arr2)

    N, M = arr1.shape
    K, _ = arr2.shape

    # Reshape arr2 to broadcast across arr1
    arr2_broadcasted = np.tile(arr2, (N, 1))
    print(np.repeat(arr2, N, axis=0))

    # Repeat arr1 K times
    arr1_repeated = np.repeat(arr1, K, axis=0)
    print(arr2_broadcasted)

    # Concatenate arr1_repeated and arr2_broadcasted along axis 1
    result = np.concatenate((arr1_repeated, arr2_broadcasted), axis=1)

    return result


# Example usage:
N, M = 3, 2
K = 2
arr1 = [[1, 2], [3, 4], [5, 6]]
arr2 = [[7], [8]]

result = concatenate_arrays(arr1, arr2)
# print(arr2_broadcasted)

[[7]
 [7]
 [7]
 [8]
 [8]
 [8]]
[[7]
 [8]
 [7]
 [8]
 [7]
 [8]]


In [30]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[1, 2]])

for bb in b:
    print(bb in a)

True


In [23]:
arr1 = np.array([[1, 2], [3, 4], [5, 6]])
arr2 = np.array([[3, 4], [5, 6]])

np.where(np.all(arr1 == arr2[0], axis=1))

(array([1]),)

In [6]:
best_indices

array(['t', 'n', 's', 'i', 'd'], dtype=object)

In [7]:
rows = maxvol(a, tol=1.005, max_iter=1000)

[ 9 13 17  8  3  5  6  7  4  0 10 11 12  1 14 15 16  2 18 19]
[[ 1.00000000e+00 -1.06546850e-16 -6.99554268e-18 -4.48572534e-17
   5.82038994e-17]
 [ 2.87555409e-17  1.00000000e+00  4.37221417e-19  2.80357834e-18
  -3.63774371e-18]
 [-8.05193143e-17  1.31092406e-16  1.00000000e+00  4.48572534e-17
  -5.82038994e-17]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
   5.45661557e-18]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00]
 [ 9.90952196e-02  1.15571414e-02  2.86562850e-01  1.49735176e-01
   2.02598936e-01]
 [-7.35807268e-02  7.71819094e-01  6.72456271e-01  6.43726354e-01
  -1.18436896e+00]
 [ 8.67938629e-01 -1.31324265e+00  2.63746115e-01 -7.95354624e-01
   8.19907383e-01]
 [ 4.13958567e-01  4.19778180e-01  9.28848138e-02 -1.03210285e-01
   2.81468141e-01]
 [-3.07688699e-01  1.81545143e-01 -2.42787196e-02  9.74204168e-01
   2.29000383e-01]
 [ 4.19524941e-01  5.50638575e-01  9.44756249e-01  5.00594743e-03
  -1.40807919e+00]
 [ 

In [8]:
abs(np.linalg.det(a[rows[0]]))

0.15091852804016956