In [1]:
import sys

sys.path.append("..")

In [2]:
import numpy as np
import numba as nb
from maxvol import maxvol, py_maxvol

In [8]:
a = np.random.rand(100, 40)

In [10]:
print(a)

[[0.6213784  0.9168328  0.66850394 ... 0.83477371 0.15657511 0.09905652]
 [0.21886436 0.86419457 0.81667763 ... 0.05138092 0.42998415 0.19257288]
 [0.30042217 0.99174986 0.65524966 ... 0.18723459 0.54849996 0.93060485]
 ...
 [0.67844533 0.68317161 0.66755376 ... 0.01128067 0.33820124 0.83653269]
 [0.0277398  0.6973895  0.77103964 ... 0.43451183 0.86980569 0.15247207]
 [0.99289027 0.61270601 0.24591954 ... 0.53387235 0.7456435  0.19796427]]


In [22]:
%%timeit
maxvol(a, tol=1.01, max_iter=1000)

4.6 ms ± 1.33 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [23]:
%%timeit
py_maxvol(a, tol=1.01, max_iters=1000)

1.91 ms ± 190 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
