In [1]:
import sys

sys.path.append("..")

In [2]:
import numpy as np
import numba as nb
from maxvol import maxvol, py_maxvol

In [3]:
a = np.random.rand(20, 4)

In [4]:
print(a)

[[0.35740568 0.63381597 0.48960773 0.20851713]
 [0.27931697 0.66464425 0.58251937 0.15919899]
 [0.81064912 0.66891429 0.88320901 0.18098887]
 [0.24183223 0.68947157 0.52749279 0.04049578]
 [0.27978466 0.93533812 0.04606056 0.26691456]
 [0.68828702 0.37747062 0.35945621 0.74076183]
 [0.93267117 0.74879242 0.49508742 0.74875179]
 [0.27375505 0.138823   0.80235514 0.62261234]
 [0.46532316 0.67499068 0.30924297 0.67138608]
 [0.63527211 0.1508062  0.24730377 0.46210099]
 [0.05752216 0.33821155 0.44713848 0.10644328]
 [0.50911192 0.38287804 0.06169358 0.19181692]
 [0.53103645 0.15703443 0.722964   0.70768079]
 [0.65954624 0.7629894  0.96501148 0.98872436]
 [0.0379292  0.75574601 0.57336213 0.2342634 ]
 [0.88791741 0.27871183 0.47914291 0.29958365]
 [0.12100095 0.12748539 0.24059119 0.20015277]
 [0.49181209 0.17927063 0.83050832 0.36091266]
 [0.17922469 0.68489872 0.47903304 0.76937766]
 [0.14308377 0.60754065 0.63834792 0.8228085 ]]


In [5]:
# %%timeit
my_rows = maxvol(a, tol=2, max_iter=1000)[0]
print(my_rows)

abs(np.linalg.det(a[my_rows]))

[ 6 14 17 19  4  5  0  7  8  9 10 11 12 13  1 15 16  2 18  3]
[[ 3.34229290e-01  1.98626413e-01  5.35499723e-01  2.09921639e-01
   7.31182524e-01  6.58658297e-01  1.00000000e+00 -2.22188687e-01
   6.09678437e-01  5.66907312e-01 -9.77660048e-02  6.82009683e-01
   1.16034915e-01  3.80633980e-01 -7.63278329e-17  7.21084197e-01
   1.72149950e-02  0.00000000e+00  1.92557840e-01  0.00000000e+00]
 [ 7.30206328e-01  9.05064249e-01  8.61201404e-01  1.08540620e+00
   8.98584281e-01 -5.01985513e-01  0.00000000e+00 -3.56369984e-01
   5.35958628e-02 -4.82903838e-01  5.19839018e-01  1.59868214e-01
  -5.56902159e-01 -7.91388192e-03  1.00000000e+00 -5.41024190e-02
  -1.53926893e-02  0.00000000e+00  9.77425912e-02  0.00000000e+00]
 [ 1.28163121e-01  2.20915102e-01  8.20123107e-01  1.61714194e-01
  -8.17750153e-01  6.87808463e-02  0.00000000e+00  7.98933150e-01
  -3.27523665e-01  2.29889880e-01  2.77183701e-01 -1.65679260e-01
   7.30205260e-01  4.24524180e-01  1.40562660e-16  5.99051927e-01
   1.6859867

IndexError: index 5 is out of bounds for axis 0 with size 4

In [ ]:
# %%timeit
rows = py_maxvol(a, tol=2, max_iters=1000)[0]
print(rows)

abs(np.linalg.det(a[rows]))

[ 4 10  1  3  0  5  6  7  8  9  2 11 12 13 14 15 16 17 18 19]
[[ 3.84217935e-01  1.10477745e-01  6.19107712e-01 -2.63960086e-01]
 [ 1.04843186e-16  2.77555756e-17  1.00000000e+00  0.00000000e+00]
 [ 8.14382561e-01  7.08072228e-01 -4.61543261e-01  1.45966322e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-8.70594513e-02 -3.65721056e-01  2.59365281e-01  5.70927437e-01]
 [ 2.56008296e-01  2.43641387e-01  3.79886270e-02  6.78423939e-01]
 [-6.13880665e-01  3.77697684e-01  7.45936444e-01  1.58629694e-01]
 [-2.61550495e-01  6.04518410e-01  1.27568090e-01  4.65391496e-01]
 [ 6.82027712e-01  9.24198145e-01 -6.81427385e-02 -1.13057289e-01]
 [-8.32667268e-17  1.00000000e+00  1.79655259e-16  7.82757287e-18]
 [ 7.43852971e-01 -3.46569975e-01  1.54370029e-01  1.77758719e-01]
 [-1.61952360e-01  5.75742650e-01  3.14867149e-01 -3.56825207e-02]
 [ 7.05483436e-01  7.99613288e-01  3.35345064e-02 -5.94068033e-01]


0.4531322895565807