In [1]:
import sys

sys.path.append("/home/ptbadia/code/tfg/tfg_ttcross/tt_cross")

In [2]:
import numpy as np
import numba as nb

from src.regular_tt_cross.dmrg_cross import greedy_cross, ttrc

In [3]:
def tsp_cost_function(x: np.ndarray) -> np.ndarray:
    cost = 0

    for i in range(1, x.shape[0] - 1, 2):
        for j in range(0, x.shape[0], 2):
            cost += x[i] * x[j]

    return cost

In [54]:
tsp_cost_function(np.array([1, 1] * 10))

90

In [55]:
ttrc_interpolator = ttrc(
    tsp_cost_function,
    20,
    np.array([[-1, 1] for _ in range(20)]),
    1e-12,
    1e-14,
    20,
    3,
    10,
    pivot_initialization="random",
)

Function successfully compiled with numba.
Initialization done after time: 0.005596160888671875 seconds and 1 tries.


In [56]:
ttrc_interpolator.run()

Sweep 1
Sweep 2
Sweep 3
Sweep 4
Sweep 5
Sweep 6
Sweep 7
Sweep 8
Sweep 9
Sweep 10
Sweep 11
Sweep 12
Sweep 13
Sweep 14
Sweep 15
Sweep 16
Sweep 17
Sweep 18
Sweep 19
Sweep 20


array([array([[[90.],
               [72.]]]), array([[0.01111111]]), array([[[90.],
                                                        [70.]]]),
       array([[0.01111111]]), array([[[90.],
                                      [72.]]]), array([[0.01111111]]),
       array([[[90.],
               [70.]]]), array([[0.01111111]]), array([[[90.],
                                                        [72.]]]),
       array([[0.01111111]]), array([[[90.],
                                      [70.]]]), array([[0.01111111]]),
       array([[[90.],
               [72.]]]), array([[0.01111111]]), array([[[90.],
                                                        [70.]]]),
       array([[0.01111111]]), array([[[90.],
                                      [72.]]]), array([[0.01111111]]),
       array([[[90.],
               [70.]]]), array([[0.01111111]]), array([[[90.],
                                                        [72.]]]),
       array([[0.01111111]]), array([[[90.],
   

In [57]:
ttrc_interpolator.eval(np.array([1, 1] * 10))

1.0065657633983138

In [58]:
ttrc_interpolator.bonds

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])